### ISSUE TITLE
No registered env with id: DepthFusionBGray-v0

### ISSUE THREAD

**Issue by sssshj** [darylperalta/ScanRL#1]
When I ran the main_unreal.py and I got error like "**gym.error.UnregisteredEnv: No registered env with id: DepthFusionBGray-v0**", could you help me and tell me the reason? BTW I have installed the required version of gym. Thank you very much.

**Comment by darylperalta** [comment]
Please follow the instructions in setting up environment in the README file specifically: _To install the environments, you need to install our fork of [gym-unrealcv](https://github.com/darylperalta/gym-unrealcv). Additional instructions are included there._.
